spring.application.name=System

spring.datasource.url=jdbc:mysql://localhost:3306/updteee?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# JWT config
jwt.secret=your_super_secret_key_123
jwt.expiration=3600000

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yasimiyuranga@gmail.com
spring.mail.password=gkljrzlxxakrzfmp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true